services:
  App\IseemoreBundle\Service\YoutubeParser:
    arguments:
      $url: '%env(string:YOUTUBE_API_URL)%'
      $key: '%env(string:YOUTUBE_API_KEY)%'

  App\IseemoreBundle\Service\Telegram\MessageToCreator:
    arguments:
      $token: '%env(string:TELEGRAM_API_TOKEN)%'
      $creatorId: '%env(string:TELEGRAM_API_CREATOR_ID)%'

  App\IseemoreBundle\Command\ParseYoutubeVideosCommand:
    arguments:
      $entityManager: '@doctrine.orm.default_entity_manager'
      $name: 'parse_youtube_videos'
      $parser: '@App\IseemoreBundle\Service\YoutubeParser'
      $sender: '@App\IseemoreBundle\Service\Telegram\MessageToCreator'
    tags: [console.command]

  App\IseemoreBundle\Controller\:
    resource: '../src/IseemoreBundle/Controller'
    tags: ['controller.service_arguments']
    calls:
      - [setContainer, ['@Psr\Container\ContainerInterface']]

  App\IseemoreBundle\Repository\:
    resource: '../src/IseemoreBundle/Repository'
    autowire: true
    tags: ['doctrine.repository_service']