version: "3.7"

services:
  youtube_nginx:
    image: nginx:1.17.8
    container_name: youtube_nginx
    ports:
      - 81:81
    volumes:
      - ./backend:/var/www/html/youtube
      - ./env/log/nginx:/var/log/nginx/
      - ./env/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - youtube_backend:youtube_backend
    networks:
      youtube:
        ipv4_address: 172.30.0.50

  youtube_backend:
    build: ./env/backend/
    container_name: youtube_backend
    volumes:
      - ./backend:/var/www/html/youtube
    networks:
       - youtube

  youtube_mysql:
    image: mysql:5.7
    container_name: youtube_mysql
    restart: always
    ports:
      - 33061:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./env/database:/var/lib/mysql
    networks:
      - youtube

  youtube_frontend:
    build: ./env/frontend/
    container_name: youtube_frontend
    volumes:
      - ./frontend:/web
    ports:
      - 8080:8080
    networks:
      - youtube

networks:
  youtube:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16